# Generated by Django 4.0.5 on 2022-08-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('phone_number', models.IntegerField()),
                ('locations', models.CharField(max_length=100)),
                ('interestedcourse', models.CharField(max_length=100)),
                ('messagesforus', models.TextField(max_length=250)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RenameModel(
            old_name='Student_info',
            new_name='EnrollCourse',
        ),
        migrations.RenameField(
            model_name='enrollcourse',
            old_name='course',
            new_name='coursename',
        ),
    ]
