# Generated by Django 4.0.5 on 2022-08-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contactinfo_rename_student_info_enrollcourse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='locations',
        ),
        migrations.AlterField(
            model_name='enrollcourse',
            name='locations',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
