# Generated by Django 4.0.5 on 2022-08-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_contactinfo_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.CharField(max_length=150),
        ),
    ]
